# Schema for the configuration files of the Storm layout builder module.
storm_layout_builder.settings:
  type: config_object
  label: 'Storm layout builder settings'
  mapping:
    example:
      type: string
      label: 'Example'
