<?php

/**
 * @file
 * Layout builder customizations by Storm.
 */

use Drupal\Core\Template\Attribute;

/**
 * Implements hook_plugin_filter_TYPE__CONSUMER_alter().
 */
function storm_layout_builder_plugin_filter_layout__layout_builder_alter(array &$definitions, array $extra) {
  unset($definitions['layout_onecol']);
}

/**
 * Implements hook_preprocess_layout().
 */
function storm_layout_builder_preprocess_layout(&$variables) {
  switch ($variables['content']['#layout']->id()) {
    case 'storm_layout_onecol':
      $class = 'l-container--onecol';
      break;

    case 'storm_layout_twocol_section':
      $class = 'l-container--twocol';
      break;

    case 'storm_layout_threecol_section':
      $class = 'l-container--threecol';
      break;

    case 'storm_layout_fourcol_section':
      $class = 'l-container--fourcol';
      break;
  }

  $variables['layout_container']['attributes'] = new Attribute([
    'class' => [
      'l-container',
      $class,
      $variables['settings']['background_color'],
    ],
  ]);
}
